/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 27 21:15:45 GMT 2026
 */

package org.apache.bookkeeper.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import org.apache.bookkeeper.util.ZeroBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
@SuppressWarnings("deprecation")
public class ZeroBuffer_ESTest extends ZeroBuffer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteBuffer byteBuffer0 = ZeroBuffer.readOnlyBuffer(65536);
      assertTrue(byteBuffer0.isReadOnly());
      assertFalse(byteBuffer0.hasArray());
      assertEquals(65536, byteBuffer0.limit());
      assertEquals(0, byteBuffer0.position());
      assertEquals("java.nio.HeapByteBufferR[pos=0 lim=65536 cap=65536]", byteBuffer0.toString());
      assertEquals(65536, byteBuffer0.capacity());
      assertTrue(byteBuffer0.hasRemaining());
      assertFalse(byteBuffer0.isDirect());
      assertEquals(65536, byteBuffer0.remaining());
      assertNotNull(byteBuffer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        ZeroBuffer.readOnlyBuffer(65555);
        fail("Expecting exception: NoSuchMethodError");
      
      } catch(NoSuchMethodError e) {
         //
         // java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
         //
         verifyException("org.apache.bookkeeper.util.ZeroBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(65542);
      assertFalse(byteBuffer0.isDirect());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertEquals(0, byteBuffer0.position());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(65542, byteBuffer0.capacity());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=65542 cap=65542]", byteBuffer0.toString());
      assertEquals(65542, byteBuffer0.remaining());
      assertTrue(byteBuffer0.hasArray());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(65542, byteBuffer0.limit());
      assertNotNull(byteBuffer0);
      
      ZeroBuffer.put(byteBuffer0, 65542);
      assertFalse(byteBuffer0.isDirect());
      assertFalse(byteBuffer0.hasRemaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(65542, byteBuffer0.capacity());
      assertEquals("java.nio.HeapByteBuffer[pos=65542 lim=65542 cap=65542]", byteBuffer0.toString());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(65542, byteBuffer0.limit());
      assertEquals(0, byteBuffer0.remaining());
      assertEquals(65542, byteBuffer0.position());
      
      ZeroBuffer.put(byteBuffer0);
      assertFalse(byteBuffer0.isDirect());
      assertFalse(byteBuffer0.hasRemaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(65542, byteBuffer0.capacity());
      assertEquals("java.nio.HeapByteBuffer[pos=65542 lim=65542 cap=65542]", byteBuffer0.toString());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(65542, byteBuffer0.limit());
      assertEquals(0, byteBuffer0.remaining());
      assertEquals(65542, byteBuffer0.position());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ZeroBuffer zeroBuffer0 = new ZeroBuffer();
      assertNotNull(zeroBuffer0);
  }
}
