/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 27 21:15:11 GMT 2026
 */

package org.apache.bookkeeper.bookie.storage.ldb;

import org.junit.Test;
import static org.junit.Assert.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import org.apache.bookkeeper.bookie.storage.ldb.ReadCache;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
@SuppressWarnings("deprecation")
public class ReadCache_ESTest extends ReadCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertNotNull(pooledByteBufAllocator0);
      
      ReadCache readCache0 = new ReadCache(pooledByteBufAllocator0, 0L);
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertNotNull(readCache0);
      
      ByteBuf byteBuf0 = readCache0.get(0L, 0L);
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertNull(byteBuf0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
      assertNotNull(pooledByteBufAllocator0);
      
      ReadCache readCache0 = new ReadCache(pooledByteBufAllocator0, 0L);
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
      assertNotNull(readCache0);
      
      readCache0.close();
      assertEquals(256, pooledByteBufAllocator0.defaultSmallCacheSize());
      assertEquals(16777216, pooledByteBufAllocator0.chunkSize());
      assertEquals(0, pooledByteBufAllocator0.defaultTinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.defaultNormalCacheSize());
      assertEquals(11, pooledByteBufAllocator0.defaultMaxOrder());
      assertEquals(0, pooledByteBufAllocator0.tinyCacheSize());
      assertEquals(64, pooledByteBufAllocator0.normalCacheSize());
      assertEquals(256, pooledByteBufAllocator0.smallCacheSize());
      assertEquals(2, pooledByteBufAllocator0.defaultNumDirectArena());
      assertTrue(pooledByteBufAllocator0.isDirectBufferPooled());
      assertEquals(2, pooledByteBufAllocator0.numDirectArenas());
      assertEquals(8192, pooledByteBufAllocator0.defaultPageSize());
      assertEquals(0, pooledByteBufAllocator0.numHeapArenas());
      assertTrue(pooledByteBufAllocator0.defaultPreferDirect());
      assertTrue(pooledByteBufAllocator0.isDirectMemoryCacheAlignmentSupported());
      assertEquals(0, pooledByteBufAllocator0.defaultNumHeapArena());
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      assertTrue(pooledByteBufAllocator0.defaultUseCacheForAllThreads());
  }
}
