name: CI

on:
  push:
    branches: [ "testing-isw2" ]
  pull_request:
    branches: [ "testing-isw2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build (no tests)
        run: mvn -U -DskipTests clean package
